Vue.component('site-skill-list', {
    props: [ 'skills' ],
    template: `<div id="skillsLanguage" v-for="(item, index) in skills" :key="index"><div class="skill-container" v-for="(i, index) in item.coding" :key="index"><p class="lang_name">{{ i.langName }}</p><div class="skill-block"><img :src="'/static/skills/' + i.image" loading='lazy' :alt="i.langName"></div></div></div>`,
});

Vue.component('projects-list', {
    props: [ 'codelist', 'selected' ],
    template: `<div class="grid-projects"><template v-for="(cd, index) in codelist" :key="index"><div class="project"><div @dblclick="$emit('select', cd)" :class="{ fullImage: selected === cd }" class="project-image" role="button"><template v-if="cd.screen"><img :src="'//screenshot.codepen.io/2727382.' + cd.src + '.' + cd.screen + '.png'" loading='lazy' :alt="cd.ifTitle"></template><template v-else><img src="/static/coming_soon.png" loading='lazy' alt="coming soon"></template></div><div class="project-about"><h4>{{ cd.projectName }}</h4><template v-if="cd.desc === null"><p class="project-caption">Explain what’s going on in your Pen here...</p></template><template v-else><p class="project-caption" v-html="cd.desc">{{ cd.desc }}</p></template><div class="project-tags" v-dragscroll:nochilddrag><i class="fas fa-tags"></i><div class="tags"><template v-for="(value, index) in cd.standard"  :key="index"><span data-dragscroll>{{ value }}</span></template><template v-for="(value, index) in cd.software"  :key="index"><span data-dragscroll>{{ value }}</span></template><template v-for="(value, index) in cd.resources" :key="index"><span data-dragscroll>{{ value }}</span></template></div></div><p class="text-right"><span @click="$emit('select', cd)" class="launch launch-right"><span class="launch-label">Запуск</span></span></p></div></div></template></div>`
});

Vue.component('projects-selected', {
    props: [ 'cd' ],
    template: `<div id="projects-full" class="pr-full"><div class="pr-container"><div class="pr-bg"></div><div class="container"><div class="pr-close" role="button" @click="$emit('close')"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 212.982 212.982" width="16" height="16"><path fill="#8d8d8d" d="M131.804,106.491l75.936-75.936c6.99-6.99,6.99-18.323,0-25.312 c-6.99-6.99-18.322-6.99-25.312,0l-75.937,75.937L30.554,5.242c-6.99-6.99-18.322-6.99-25.312,0c-6.989,6.99-6.989,18.323,0,25.312 l75.937,75.936L5.242,182.427c-6.989,6.99-6.989,18.323,0,25.312c6.99,6.99,18.322,6.99,25.312,0l75.937-75.937l75.937,75.937 c6.989,6.99,18.322,6.99,25.312,0c6.99-6.99,6.99-18.322,0-25.312L131.804,106.491z" /></svg></div><div class="pr-content"><h3 class="pr-title">{{ cd.projectName }}</h3><div class="pr-desc"><template v-if="cd.desc === null"><p class="project-caption" style="color:#a4a4a4;">Explain what’s going on in your Pen here...</p></template><template v-else><p class="project-caption" v-html="cd.desc">{{ cd.desc }}</p></template><template v-if="cd.alert"><div v-for="(value, name, index) in cd.alert" class="alert" :class="name">{{ value }}</div></template></div><template v-if="cd.about"><h3 class="pr-stage">Приемы и css свойства</h3><ul class="dots"><template v-for="(name, index) in cd.about"><li>{{ name }}</li></tempalte></ul></tempalte><div class="pr-date text-right"><small><strong>Дата: </strong>{{ cd.date }}</small></div><h3 class="pr-stage">Структура кода</h3><div class="pr-devs"><details class="dt" open><summary>Standard</summary><ul class="dots"><template v-for="(value, index) in cd.standard" :key="index"><li>{{ value }}</li></template></ul></details><template v-if="cd.software"><details class="dt" open><summary>Software</summary><ul class="dots"><template v-for="(value, index) in cd.software" :key="index"><li>{{ value }}</li></template></ul></details></template><template v-if="cd.resources"><details class="dt" open><summary>Resources</summary><ul class="dots"><template v-for="(value, index) in cd.resources" :key="index"><li>{{ value }}</li></template></ul></details></template></div><div class="pr-block"><div class="pr-image"><div class="pr-prev" data-no-dragscroll><template v-if="cd.src"><iframe style="width: 100%;" :title="cd.ifTitle" class='pr-src' :src="'https://codepen.io/andrejsharapov/embed/preview/' + cd.src + '?height=365&theme-id=light&default-tab=css,result'" frameborder='0' scrolling='no' allowtransparency='true' allowfullscreen='true'></iframe></template><template v-else><img src="/static/coming_soon.png" loading='lazy' alt="coming soon"></template></div></div></div></div></div></div></div>`,
});